Feature/firebase realtime database
quarkiverse/quarkus-google-cloud-services pull request #724
Opened 2024-12-20 14:51 UTC by jfbenckhuijsen

Fixes https://github.com/quarkiverse/quarkus-google-cloud-services/issues/133

This PR depends on 707, hence don't merge it yet.

2025-01-13 18:03 UTC, jfbenckhuijsen commented on firebase-devservices/deployment/src/main/java/io/quarkiverse/googlecloudservices/firebase/deployment/FirebaseDevServiceProcessor.java
> -            FirebaseEmulatorContainer.Emulator.REALTIME_DATABASE, "quarkus.google.cloud.database.emulator-host",
That property was not yet actively used from the dev service, so I synced it with the other modules

2025-01-13 18:03 UTC, jfbenckhuijsen commented on docs/modules/ROOT/pages/firebase-database.adoc
> +This extension allows to inject a `com.google.cloud.firestore.Firestore` object inside your Quarkus application.
Whoops, good catch

2025-01-17 08:30 UTC, loicmathieu commented
@jfbenckhuijsen my question was more of Firestore vs Firebase.
But I'm also a little concern about the cost to add a new extension if there already exist one with the same lib.

2025-01-17 08:36 UTC, jfbenckhuijsen commented
> @jfbenckhuijsen my question was more of Firestore vs Firebase. But I'm also a little concern about the cost to add a new extension if there already exist one with the same lib.

Ah ok, clear. Firebase Realtime Database to my knowledge is a different product (with a different goal) than Firestore. 

I can rewrite the extension to be part of the firebase-admin extension (this one has the same dependency). Downside is that the name would then not really fit the goal of that existing extension (we probably should rename it to -firebase instead of -firebase-admin, but that;s an backwards incompatible change ofc).

2025-01-17 09:57 UTC, loicmathieu commented
OK, let's keep both.

By the way, I plan to do a release soon so it's been available in the next Quarkus release but there is a test related to your recent changes that fails in the Quarkiverse CI which test this extension with the main branch of Quarkus.

If you can have a look it would be great otherwise I'll have a look later.

See https://github.com/quarkiverse/quarkus-google-cloud-services/actions/runs/12823020927/job/35756877903

2025-01-17 13:11 UTC, jfbenckhuijsen commented
> OK, let's keep both.
> 
> By the way, I plan to do a release soon so it's been available in the next Quarkus release but there is a test related to your recent changes that fails in the Quarkiverse CI which test this extension with the main branch of Quarkus.
> 
> If you can have a look it would be great otherwise I'll have a look later.
> 
> See https://github.com/quarkiverse/quarkus-google-cloud-services/actions/runs/12823020927/job/35756877903

@loicmathieu Looking at the error, I think (but logging is quite limited) that the issue is caused by the fact that we made some changes to the build CI script, which aren't reflected in the Quarkus snapshot build (i.e. the NPM stuff and the current user stuff). I can have a go at creating a PR for that, but would probably need some help there as I'm not really familiar with those scripts and tests.

2025-01-17 14:30 UTC, loicmathieu requested changes
Can you update the doc to match the correct extension name, then we're good to merge :tada:

2025-01-17 17:03 UTC, jfbenckhuijsen commented on docs/modules/ROOT/pages/firebase-database.adoc
Fixed and also saw a copy/paste error in the devservices module Nav.adoc. Also fixed that

2025-01-17 17:04 UTC, jfbenckhuijsen commented on docs/modules/ROOT/pages/firebase-database.adoc
@loicmathieu we should be good to go (once build finishes correctly)

2025-01-26 22:51 UTC, jfbenckhuijsen commented
> LGTM, thanks, can you squash your commits in one so I can merge?

done

2025-01-27 12:09 UTC, merged

2025-01-28 12:56 UTC, jfbenckhuijsen commented
@loicmathieu can we close #133 now?

2025-01-28 13:32 UTC, loicmathieu commented
Yes, it's closed already ;)